export const rolePermissions = {
    Developer:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
        "saveClassify",
        "saveReview",
        "cancelProcess",
        "closeClassify",
    ],
    Admin:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
    ],
    Coordinator:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
        "cancelProcess",
        "closeClassify"
    ],
    Reviewer:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
        "saveReview",
        "cancelProcess"
    ],
    Classifier:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
        "saveClassify",
        "cancelProcess"
    ],
    Accunting:[
        "create",
        "edit",
        "delete",
        "classify",
        "save",
    ]
}